### ISSUE TITLE
www to non-www

### ISSUE THREAD

**Issue by alvipeo** [aspnet/BasicMiddleware#193] opened 2016-12-20 23:23 UTC
Hi! I'm trying to do a simple thing - force 301 for www to non-www. Like described here - http://stackoverflow.com/questions/41205435/asp-net-core-1-1-url-rewriting-www-to-non-www. Can you please tell me why it doesn't work?

Thank you!

**Comment by jkotalik** [comment] 2016-12-21 00:39
Hey, I just added a response on SO. The issue is that the regex match is done on the path/query string rather than the whole URL. This is standard for most/ all url rewriters, so I created a quick custom one with an Action<RewriteContext>.

**Comment by muratg** [comment] 2017-01-10 18:08
Closing this and keeping #194 open instead.

**Closed** 2018-10-16 21:15 UTC
