### ISSUE TITLE
OverrideHeaderMiddleware doesn't handle X-Forwarded-For inside a docker container

### ISSUE THREAD

**Issue by lmcarreiro** [aspnet/BasicMiddleware#361] opened 2018-09-10 12:42 UTC
Test with Fiddler and Docker for Windows, running inside Visual Studio it works fine, I get the `RemoteIpAddress` with the value from the `X-Forwarded-For` header.
If I run inside docker, I get something like this: `::ffff:172.23.112.1`

I'm using ASP.NET Core 2.2.0-preview1-35029

**Comment by Tratcher** [comment] 2018-09-10 13:51
Duplicate of https://github.com/aspnet/BasicMiddleware/issues/358 which was fixed in preview3. A workaround was also added to the docs: https://github.com/aspnet/Docs/pull/8432,

**Closed by Tratcher** 2018-09-10 13:51 UTC
